export const APPWRITE_API_ENDPOINT = import.meta.env.VITE_APPWRITE_API_ENDPOINT
export const APPWRITE_PROJECT_ID = import.meta.env.VITE_APPWRITE_PROJECT_ID
export const APPWRITE_DB_ID = import.meta.env.VITE_APPWRITE_DB_ID
export const APPWRITE_CHALLENGES_TABLE_ID = import.meta.env.VITE_APPWRITE_CHALLENGES_TABLE_ID